#!/usr/bin/env bash
#
# Run all dotfiles installers.

set -e

cd "$(dirname $0)"/..

# Run Homebrew through the Brewfile
if [[ $(command -v brew) ]]; then
  echo "› brew bundle"
  brew bundle
fi

# find the installers and run them iteratively
find . -name install.sh | while read installer ; do echo Executing ${installer}; sh -c "${installer}" ; done
